### ISSUE TITLE
Projectile replacements do not respect sym links

### ISSUE THREAD

**Issue by Lugoues** [Malabarba/smart-mode-line#125]
I was able to fix this by changing line 1653 to `(abbreviate-file-name (file-truename in)))` which didn't seem correct since `sml/replacer` is attempting to do the same. I am new to the emacs world so `sml/replacer` was a bit much for me to tackle.

~/dev => ~/Documents/dev is the symlink

**Comment by Malabarba** [comment]
Thanks for reporting this. I'll fix it later today. The fix is a little different from that because I still want to preserve the current functionality (replacing over the hardlinked name), but it's pretty simple.

Cheers

**Comment by Malabarba** [comment]
Should be fixed. Let me know if it works.

**Comment by Lugoues** [comment]
Still broken, same reason.
```
(replace-regexp-in-string
             (concat "^" (regexp-quote (abbreviate-file-name (file-truename proj))))
             replacement
             in)
```
`in` comes in as (sml/get-directory) => ~/dev/...
(abbreviate-file-name (file-truename (projectile-project-p))) => ~/Documents/dev/...

Since `in` isn't expanded the regexp fails.

**Comment by Lugoues** [comment]
That fixed it! Thanks!
