### ISSUE TITLE
Error during redisplay when opening calc

### ISSUE THREAD

**Issue by kurnevsky** [Malabarba/smart-mode-line#240]
Steps to reproduce:

- emacs -Q --load ~/.emacs.d/elpa/rich-minority-20190419.1136/rich-minority.el --load ~/.emacs.d/elpa/smart-mode-line-20190327.1941/smart-mode-line.el
- Switch to `*Messages*`
- M-x sml/setup y
- C-x * *

You'll see:

> Error during redisplay: (eval (sml/generate-buffer-identification-if-necessary)) signaled (wrong-type-argument listp "Calc: 12 Deg               ")

**Comment by Malabarba** [comment]
Thankss for the report. Should be fixed now.

**Comment by kurnevsky** [comment]
@Malabarba It seems it's not fixed - I still get this error.

**Comment by Malabarba** [comment]
Ok, let's try that again. Pushed a new fix. :-)

**Comment by kurnevsky** [comment]
Fixed now, thanks :)
